project:
  type: website
  output-dir: docs

website:
  title: "Meaningful Associations Redux"
  site-url: https://anthonystevendick.github.io/Meaningful-Effects-Redux
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: effect_size_overlap.qmd
        text: Overlap Plot
      - href: halsey_simulation.qmd
        text: Halsey Simulation
      - href: power_curves.qmd
        text: Power Curves
      - href: barplot_scatterplot.qmd
        text: Barplot
